// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtylYvL3G49s_yfDMvKlNZsvKKkv4_I8Y',
    appId: '1:762722484360:web:f2b14077c697af0f889f3d',
    messagingSenderId: '762722484360',
    projectId: 'reclaim-d09e4',
    authDomain: 'reclaim-d09e4.firebaseapp.com',
    storageBucket: 'reclaim-d09e4.firebasestorage.app',
    measurementId: 'G-Z9B0E7LLZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6mtuGI96PsZQLJ6PAf8iROn9emwEWnA',
    appId: '1:762722484360:android:cc09a58cf27e0c83889f3d',
    messagingSenderId: '762722484360',
    projectId: 'reclaim-d09e4',
    storageBucket: 'reclaim-d09e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJp7d-cm9jj4JgeKDuo_ByF46HfJu8wY',
    appId: '1:762722484360:ios:fa89cff95874484c889f3d',
    messagingSenderId: '762722484360',
    projectId: 'reclaim-d09e4',
    storageBucket: 'reclaim-d09e4.firebasestorage.app',
    iosBundleId: 'com.example.reclaim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJp7d-cm9jj4JgeKDuo_ByF46HfJu8wY',
    appId: '1:762722484360:ios:fa89cff95874484c889f3d',
    messagingSenderId: '762722484360',
    projectId: 'reclaim-d09e4',
    storageBucket: 'reclaim-d09e4.firebasestorage.app',
    iosBundleId: 'com.example.reclaim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtylYvL3G49s_yfDMvKlNZsvKKkv4_I8Y',
    appId: '1:762722484360:web:393769fe2ec2772c889f3d',
    messagingSenderId: '762722484360',
    projectId: 'reclaim-d09e4',
    authDomain: 'reclaim-d09e4.firebaseapp.com',
    storageBucket: 'reclaim-d09e4.firebasestorage.app',
    measurementId: 'G-WTQTQVZY3Q',
  );
}
